name: env-dc-swot-denoising
channels:
  - pyviz
dependencies:
  - python=3.10
  - conda-forge::numpy=1.22.4
  - pandas=2.1.1
  - scipy
  - hvplot
  - conda-forge::pyinterp
  - conda-forge::cmocean
  - holoviews
  - geoviews
  - cartopy=0.21
  - tabulate
  - datashader
  - netcdf4
  - conda-forge::ffmpeg
  - pip
  - pip:
    - mycolorpy
